apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=

#Storing the data in a Secret component doesn't automatically make it secure.
#There are built-in mechanism (like encrytion) for basic security, which are not enabled by default.